### ISSUE TITLE
WEIRD instruction and test from Lab for #Create Redirect.  

### ISSUE THREAD

**Issue by kostanzhoglo** [learn-co-students/rails-form_tag-lab-v-000#668]
Hello, 

Here's a link to a previous issue with this same lab, from **2016**.  Please fix this, it's more than 2 years old.

https://github.com/learn-co-curriculum/rails-form_tag-lab/issues/7

I had the same issue late last night and this morning.
Here's the situation:
A user fills out a form on the views/students/new.html.erb
Info is sent to #Create action in the students_controller.rb
NORMALLY, from a #Create action, the New Student would be redirected to the students_path.

BUT, in this lab, it's instructing me to redirect BACK to the new.html.erb view.
WHY exactly are we doing this?  
I kept trying to do just that in my lab code, and kept getting an error.
BUT, when I tried `redirect_to students_path` (the normal #create redirect), I passed the remaining test and finished the lab.

Can someone please fix this weird instruction, or explain how to pass it?
It wasted an hour for me, and I'd prefer it if no one else had to struggle with this strange test.  Or get more instruction on how to pass it, and why it's important.

Thank you!
Best,
J

**Comment by FionaDL** [comment]
I also had this issue, and spent at least an hour trying to figure out why my tests wouldn't pass. I hope someone will fix this issue soon.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
